language: objective-c

before_install:
        - cd Spec
        - pod install

script:
        - xcodebuild build -workspace Spec.xcworkspace -scheme Spec -derivedDataPath build
        - build/Build/Products/Debug/Spec
